spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/TaskManagerRealm
  jpa:
    hibernate:
      ddl-auto: update


server:
  port: 8081


keycloak:
  server-url: http://localhost:8080/
  realm: TaskManagerRealm
  client-id: task-manager-app
  client-secret: 0hCg78je0jFhligxbkZICr3DWxhbHZWK
  username: admin
  password: admin

groups:
  admin:
    path: "/Users/Manager/Admin"
  manager:
    path: "/Users/Manager"
